### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by VaslD** [markjfisher/tesl-java-sdk#1]
There are duplicate cards in [the resource folder](https://github.com/markjfisher/tesl-java-sdk/tree/master/sdk/src/main/resources/cards). I wasn't using Kotlin so I didn't run your original code. From what I can tell, you were reading all JSON resources regardless, that means these duplicates will be added twice into memory cache. (Forgive me if my Kotlin's wrong.)

According to the endpoint the online SDK pulls, there are 1212 cards available (as of now); but there are 1361 files in the resource. So I wrote a collision test:

- _Redacted List_

It **looks like** (I didn't check all) these dups have the same stats as their counterparts, but with a different *Code* and a different *ID*, which I assume is a GUID you maintain personally because they don't match the online card data either.

Then I thought maybe you were trying to do a multimapping from cards to short codes. I went over to [the mapping file](https://github.com/markjfisher/elder-scrolls-legends-sdk-java/blob/master/sdk/src/main/resources/decoder-map-all.json) your decoder reads, as it turned out codes for the duplicate cards didn't exist in the map keys.

Is there a reason you keep these duplicates? I'm asking because if the reason is personally or for BC of this project, I won't be needing them in my project then.

**Comment by markjfisher** [comment]
Hi @VaslD thanks for the interest!

The dupes are alt-art versions of the cards (they have additional field of "isAlt = true"). I was thinking about modelling this better by holding a field on the original card to its alt art, but eventually the imageUrl is going to be different for them. Right now, I don't have the images for them, so I'm effectively mapping them all down to the same card - which also means when people view a deck with an alt-art card, it shows the standard card graphic, which I think is a bit better, but that may change.

In the bot code, it filters the dupes out of searches with ".filter { !it.isAlt }" (https://github.com/markjfisher/tesl-java-sdk/blob/master/rest/src/main/kotlin/tesl/bot/CardCommands.kt#L54).

The ID field is just for completeness, as they are individual resources, it's a UUID based on the card name and card code, just so I can have separate IDs somewhere if I ever need them (e.g. REST endpoint to get stats back on the card)

The mapping file you linked is old and not used by the SDK. It was part of me maintaining a link between my original SDK and the database on https://docs.elderscrollslegends.io/ and I only used that as part of the conversion from my old SDK (https://github.com/markjfisher/elder-scrolls-legends-sdk-java) to this one, so don't rely on that.

**Comment by markjfisher** [comment]
I am going to have a think about the alt-art resources and remove some of them. I haven't pushed a public release of these yet, and may back them out. For now, if you're going from source, filter on isAlt field.

**Comment by VaslD** [comment]
Thank you for this very thorough explanation.

I understand your logic, different cards are different cards. But to be frank modeling alt arts this way is weird. I’d make `imageUrl` (and `code` if applicable) a collection, but (1) that would be a breaking change from current code; (2) it won’t work well if summoning costs are different for alt cards (didn’t notice in game, is it a thing in TESL?).

Maybe an `alternatives` field? I‘m not sure. I just think there should be some sort of relationship indication between base and alts, and reusing immutable stats if you can.

**Comment by markjfisher** [comment]
Now I know there's at least one other person looking at my code, I'll make more valued judgements on my modelling decisions :)

I think you're right, I'm going to roll back those changes to isAlt, and do it better. This was a particularly quick hack to get them available.

However, I need to actually visit whether deck exports actually can have the alt-art codes in them or not (a quick check seemed to indicate not) so they may not be needed at all.
e.g. if I export a deck with Murkwater Witch alt that I have in my collection, it exports with code "lh" which is the original card's export code.
